version: '3.7'

x-node-defaults: &node
  tty: true
  init: true
  image: node:10.15
  entrypoint: ["node"]
  working_dir: /root
  restart: always
  volumes:
    - ./:/root:cached
    - ./node_modules:/root/node_modules:delegated
    - yarn-cache:/.yarn-cache

x-newsletter-command: &newsletter-cmd
  entrypoint: ["node_modules/.bin/basecms-newsletters"]
  command: ["dev", "index.js"]

x-env-defaults: &env
  YARN_CACHE_FOLDER: /.yarn-cache
  NODE_ENV: development
  NEW_RELIC_ENABLED: ${NEW_RELIC_ENABLED-0}
  NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY-(unset)}

x-env-caprica: &env-caprica
  GRAPHQL_URI: ${GRAPHQL_URI-https://caprica.graphql-staging.base-cms.io}

services:
  terminal:
    <<: *node
    working_dir: /root
    entrypoint: ["/bin/bash"]
    environment:
      <<: *env

  yarn:
    <<: *node
    working_dir: /root
    entrypoint: ["yarn"]
    environment:
      <<: *env

  ien:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/ien
    environment:
      <<: *env
      <<: *env-caprica
      PORT: 80
      EXPOSED_PORT: 21090
      LIVERELOAD_PORT: 31090
      TENANT_KEY: indm_ien
    ports:
      - "21090:80"
      - "31090:31090"

  all:
    <<: *node
    <<: *newsletter-cmd
    working_dir: /root/tenants/all
    environment:
      <<: *env
      <<: *env-caprica
      PORT: 80
      EXPOSED_PORT: 21091
      LIVERELOAD_PORT: 31091
      TENANT_KEY: indm_all
    ports:
      - "21091:80"
      - "31091:31091"

volumes:
  yarn-cache: {}
